# Generated by Django 3.1.2 on 2021-01-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='horaPartido',
        ),
    ]
